from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, Protocol, runtime_checkable


@dataclass(frozen=True)
class DriverInfo:
    key: str
    name: str
    device_type: str
    vendor: str = "Generic"
    description: str = ""


@runtime_checkable
class BmsDriver(Protocol):
    def connect(self) -> bool: ...
    def close(self) -> None: ...
    def read_telemetry_snapshot(self) -> Dict[str, Any] | None: ...
    def get_point_catalog(self) -> Dict[str, Dict[str, Any]]: ...
    def read_software_version(self, sbmu_count: int = 0) -> Dict[str, Any]: ...
    def read_debug_status(self) -> Dict[str, Any]: ...
    def write_heartbeat(self, value: int) -> bool: ...
    def clear_fault(self) -> bool: ...
    def write_ems_cmd_stay(self) -> bool: ...
    def write_ems_cmd_power_on(self) -> bool: ...
    def write_ems_cmd_power_off(self) -> bool: ...


@runtime_checkable
class PcsDriver(Protocol):
    def connect(self) -> bool: ...
    def close(self) -> None: ...
    def get_active_power(self) -> float: ...
    def set_active_power(self, value: float) -> bool: ...
    def get_fault_status(self) -> int: ...
    def is_dc_breaker_open(self) -> bool: ...
    def is_dc_breaker_closed(self) -> bool: ...
    def start_with_confirm(self) -> bool: ...
    def stop_with_confirm(self) -> bool: ...
    def reset_fault(self) -> bool: ...
    def hv_on(self) -> bool: ...
    def hv_off(self) -> bool: ...
